"""Added User object

Revision ID: 92466426ca73
Revises: 
Create Date: 2020-04-21 17:07:52.552455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92466426ca73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_unique_constraint(None, 'news_item', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_item', type_='unique')
    op.drop_table('user')
    # ### end Alembic commands ###
